import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans, Julee } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";

export const fontSans = FontSans({
   subsets: ['latin'],
   variable: '--font-sans'
})

export const julee = Julee({
   weight: ['400'],
   subsets: ['latin'],
   variable: '--font-julee'
})

export const metadata: Metadata = {
   title: "Sushi App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-BR" suppressHydrationWarning>
         <body
            className={cn(
               'min-h-screen bg-background font-sans antialiased',
               fontSans.variable, julee.variable
            )}
         >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
         </body>
      </html>
   );
}